fix uv add error
fix error while using uv add
```
(base) (polymarket) PS D:\Programing\polymarket> uv add https://github.com/hbr-l/polypy.git
 Updated https://github.com/hbr-l/polypy.git (bd9a728)
error: The build backend returned an error                                                                                             
  Caused by: Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit code: 1)

[stderr]
C:\Users\Doiiars\AppData\Local\uv\cache\builds-v0\.tmpMNIZJg\Lib\site-packages\setuptools\_distutils\dist.py:289: UserWarning: Unknown distribution option: 'install_requirements'
  warnings.warn(msg)
error in polypy setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

hint: This usually indicates a problem with the package or the build environment.
```